module.exports={
    USER_COLLECTION:'user',
    PRODUCT_COLLECTION:'product',
    CART_COLLECTON:'cart',
    CATEGORY_COLLECTION:'category',
    ORDER_COLLECTION:'order',
    COUPON_COLLECTION:'coupons',
    USED_COUPON_COLLECTION:'usedCoupons',
    WISHLIST_COLLECTION:'wishlist',
    ADDRESS_COLLECTION:'address',
    BANNER_COLLECTION:'banners'
}